### ISSUE TITLE
Graph <-> Math Equations library

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/model-service#30]
We need a library to transform PetriNet/ODE to MathML/LaTex and vice-versa.

**Comment by ChrisRackauckas** [comment]
The conversion to LaTeX is automatic if it's in ModelingToolkit form. You can see this in our documentation: https://docs.sciml.ai/ModelingToolkit/stable/tutorials/acausal_components/#Connecting-and-Simulating-Our-Electric-Circuit

So if the connection to TA3 works fine, then there's nothing required on the TA2 team to actually output this. So, 🤞 it all "just works"

**Comment by bgyori** [comment]
That sounds good! Let me know if anything comes up that we can improve on though.

**Comment by liunelson** [comment]
I've tested @adarshp's SKEMA MathML-to-PetriNet API endpoint
[https://skema-rs.staging.terarium.ai/mathml/acset](https://skema-rs.staging.terarium.ai/mathml/acset)
Based a few simple test cases (SIR-type ODE systems), it works!

I'll continue to test using more complicated models (vaccination, quarantine, SIDARTHE, stratified versions).
I'll also test @ChrisRackauckas's MTK-to-LaTeX using the same models to see if we can close the loop.

**Comment by liunelson** [comment]
@ChrisRackauckas 
How do I get the LaTeX form of a `ODESystem`?
Example: https://github.com/DARPA-ASKEM/experiments/blob/main/notebooks/Nelson/model-repr-conversion/petri-to-equations.ipynb

**Comment by ChrisRackauckas** [comment]
```julia
using Latexify
latexify(sys)
```

**Comment by liunelson** [comment]
@adarshp 
Some issues with the SKEMA equation (MathML) to Petri net (ACSet) converter.
* I currently just get a code 502 whenever something goes wrong. Can you provide a bit more to let someone like me diagnose what went wrong with the conversion. I got a 502 for all the points below and I'm forced to do trial-and-error to discover what the limitations of the service are.
* The current service throws a 502 when I send `=, +, -` as `&#x0003D;, &#02212;, &#0002B;`. Can you update it to handle unicode better?
* When I send the equations `d A / d t = 0`, it returns a Petri net of the form `"0" -> "A"` where `"0"` is a transition node. I'd have expected the correct response should be just a trivial Petri net with just a single species node `"A"` and nothing else.

![Image](https://user-images.githubusercontent.com/1030720/225126779-3cc0eb00-6595-4d03-84d0-472300ed17b4.png)

**Comment by adarshp** [comment]
@liunelson  - thanks for bringing these issues to our attention. Unfortunately I won't be able to get to this until next week, hope that is ok for you timeline-wise.

**Comment by adarshp** [comment]
@liunelson  - could you also share example JSON inputs that trigger the errors you described? We can then write unit tests to make sure those are handled.

**Comment by liunelson** [comment]
@adarshp 
Here they are:
*  Equations that gives an incomplete Petri net (missing edges); [the correct Petri net](https://github.com/DARPA-ASKEM/experiments/blob/main/notebooks/Nelson/multi-stratify-experiment/model_petri_age.json):
`[
    r"\frac{d A_1}{dt} = - 2 a_{11} A_1 A_1 - 2 a_{11} A_1 A_1 + a_{11} A_1 A_1 + a_{11} A_1 A_1 + a_{12} A_1 A_2 - a_{12}A_1 A_2 - a_{21} A_2 A_1 + a_{21} A_2 A_1",
    r"\frac{d A_2}{dt} = - 2 a_{22} A_2 A_2 - 2 a_{22} A_2 A_2 + a_{22} A_2 A_2 + a_{22} A_2 A_2 + a_{12} A_1 A_2 - a_{12}A_1 A_2 - a_{21} A_2 A_1 + a_{21} A_2 A_1"
]`

*  Equations that gives an incorrect Petri net with `0` as a transition node; the correct Petri net should be just two unconnected nodes `A_1, A_2`:
`[
    r"\frac{d A_1}{d t} = 0",
    r"\frac{d A_2}{d t} = 0"
]`

**Comment by adarshp** [comment]
@liunelson  - our system expects MathML inputs, not LaTeX inputs. Do you have the MathML versions of these?

**Comment by liunelson** [comment]
@adarshp 
[broken_1.txt](https://github.com/DARPA-ASKEM/model-service/files/10991828/broken_1.txt)
[broken_2.txt](https://github.com/DARPA-ASKEM/model-service/files/10991829/broken_2.txt)

Related issue: 
`latexify` in Julia converts SciML models as LaTeX that uses for example `\begin{align} ... \end{align}`, `\mathrm{...}`, `\left( t \right)`. From my experience, I need to break up a single "aligned" expression into a list before converting it into MathML using `latex2mathml` and sending it to SKEMA. Similarly, I need to strip `\mathrm{...}` and `\left( t \right)` first. Can SKEMA be updated to handle them?

Also, MathML uses numeric character references `&#x...;`. Can SKEMA not pass those on in the ACSet by applying the Rust equivalent of `html.unescape(...)` which maps for example `&#x03B2` back to `β`?

**Comment by liunelson** [comment]
Just including here the PR from Yingbo at JuliaHub that potentially fixes the lossy conversion between Petri net and LaTeX equation representations in the case of some dynamic-equilibrium models (e.g. contact, vacc models used in stratification).
https://github.com/AlgebraicJulia/AlgebraicPetri.jl/pull/115

**Comment by adarshp** [comment]
Thanks @liunelson !

**Comment by liunelson** [comment]
@adarshp You might have heard of the new "ASKEM model representation" schema. 

It's basically a JSON object that stores model "properties" where one of them is "model" holds the JSON serialization of a Petri net (or any other model types).

[Base Schema](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/base_schema.json)
[Petri Net Schema](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/petrinet/petrinet_schema.json)

When might your team be able to roll this out?

**Comment by Free-Quarks** [comment]
It's on our to-do's, but still about a 1-2 weeks out. Once the 4/25 demo next week is over, it'll be prioritized!

**Comment by liunelson** [comment]
@mehalter 
Is there a Julia function that takes a model in AMR JSON and returns a (Typed)LabelledPetriNet that in turn can be converted into a SciML ODEProblem?

**Comment by mwdchang** [comment]
Moved to sciml. Model-service is no longer in use.
