### ISSUE TITLE
[TASK]: Deep dive into PetriNet stratification

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/model-service#6]
**Describe the task**
- Meet with TA2 UoF to understand all the ins and outs of PetriNet stratification
- Write a stratification API endpoint proposal for use in #12

**Comment by bencodrington** [comment]
@Tom-Szendrey when you get a chance, please add the new information from Kristopher to your Catlab knowledge document and add it to the shared google drive.

Then we can link it here and close this ticket.
