### ISSUE TITLE
[TASK]: Make the `model-transform` API stateless

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/model-service#7]
**Describe the task**
- As of now the `model-transform` service is keeping the models in memory.
- The service should be stateless and all data (models, action, parameters, etc.) should be send with each request.
- Update the API Documentation to reflect this changes
- Keep in mind in the _HMI backend_ that those data will come from the _HMI frontend_ and the _Data Service_

**Comment by mwdchang** [comment]
Still need to do stratify and compose, but these two still have dangling questions that need to be resolved. Otherwise this is done.
